### ISSUE TITLE
Do not sort postgresql.conf settings

### ISSUE THREAD

**Issue by tgoodaire** [sous-chefs/postgresql#274]
The postgresql.conf template sorts the configuration:
<% node['postgresql']['config'].sort.each do |key, value| %>

This will cause problems if you would like to use the "include" directive. This must go at the end of the file, or its settings may be overridden by other values. (Plus, apart from wanting the config file to look nice, there's no reason to sort.)

**Comment by sfiggins** [comment]
It's not just to look nice.  Sorting means we are less sensitive to insert order changes triggering a rewrite and reload of the configuration.  

Also, if we don't order the keys, includes would still have to be inserted last, which might not always be preferable.  Seems like we would still need a way to ensure includes go last in the conf, and probably in a specific order. 

If you have strong needs around configuration file order, you might just want to use your own template.  Making it easier to substitute a template or to call a recipe instead of server_conf might be the better solution.

**Comment by tgoodaire** [comment]
Ah. That makes sense. We can't guarantee the ordering of the keys. 

As a workaround, I've been working on my own template. Thanks for your help and suggestions.

**Comment by carltonstedman** [comment]
I believe this PR may make it easier to use templates from another cookbook in the server_conf.rb recipe: https://github.com/hw-cookbooks/postgresql/pull/275
