### ISSUE TITLE
Postgresql 9.5 support

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/postgresql#323]
I'm upgrading PostgreSQL to 9.5 on Ubuntu 14.04. First issue is that I need to specify *-9.5 packages:

```
   "client": {
      "packages": ["postgresql-client-9.5","libpq-dev"]
    }, 
    "server": {
      "packages": ["postgresql-9.5"]
    },
    "contrib": {
      "packages": ["postgresql-contrib-9.5"]
    }
```

It's not enough to specify `version` only.

Second issue is that `checkpoint_segments` option is [replaced](http://www.depesz.com/2015/02/25/waiting-for-9-5-replace-checkpoint_segments-with-min_wal_size-and-max_wal_size/).

Most likely there are other things to fix.

**Comment by andrefreitas** [comment]
+1 for this issue

**Comment by chr4** [comment]
The versioning problem is even worse. https://github.com/hw-cookbooks/postgresql/issues/319

**Comment by sauliusgrigaitis** [comment]
@chr4 yes, that's big fuckup. At least we can live with workaround I wrote above.

**Comment by chr4** [comment]
Partially. I think you need to specify the `node['postgresql']['dir']` `node['postgresql']['config']['data_directory']`  variable as well, and it breaks SSL, see my Issue for details.

AND IT GETS WORSEL - If you had used version 9.4, the cookbook automatically installs `postgresql-9.3` because of this bug. And it then uses the 9.4 data/ config directories because you need to specify them manually. If you then use `apt-get purge postgresql-9.3` to get rid of 9.3 again, it DELETES THE WHOLE 9.4 CLUSTER. This happened exactly like this to one of my staging environments.

**Comment by sauliusgrigaitis** [comment]
@chr4 I had exactly same experience as you, I had PostgreSQL 9.4 installed and this cookbook update dropped my database. Backups were in place.

Yes, my full working config is: 
```
  "postgresql": {
    "config_pgtune": {
      "db_type": "...",
      "total_memory": "..."
    },
    "version": "9.4",
    "dir": "/etc/postgresql/9.4/main",
    "client": {
      "packages": ["postgresql-client-9.4","libpq-dev"]
    }, 
    "server": {
      "packages": ["postgresql-9.4"]
    },
    "contrib": {
      "packages": ["postgresql-contrib-9.4"],
      "extensions": ["..."]
    },
    "password": {
      "postgres": "*"
    }
  }
```
Anyway, it's ultimate fuckup. I will not be so confident after ```berks update``` any more.

**Comment by chr4** [comment]
It kind of feels like we might need to fork the repo, as there's not answer since 9 days..

**Comment by sauliusgrigaitis** [comment]
This repo has more forks than stars...

**Comment by luckymike** [comment]
@sauliusgrigaitis et al,

Thank for you reporting this and sharing examples. We're aware that the latest version has issue with 9.4. and 9.5. We're working to address these as we can, but as we receive no compensation for working on this cookbook, we do need to balance this work with other priorities. 

We're also very open to any PRs that resolve the issue, or help bring it closer to resolution.

**Comment by sauliusgrigaitis** [comment]
@luckymike don't get me wrong, I appreciate your efforts, that's why I reported issue and provided workaround. Probably best would be to ditch 4.0.0 version from the market and maybe even revert those commits until somebody gets time to fix it.

**Comment by slyness** [comment]
No. Pin your Berksfile, Cheffile or metadata dependency to the 3.x series if you don't want to use the 4.x release yet. There are many other changes in this release which finally start moving the code base forward again around testing and the removal of the old way attributes were incorrectly being dynamically set.

We will continue forward with the 4 release. There were to many things already going wrong with the state of the last few 3.x releases which the existing code base could no longer support or keep up with. That's why a new major release was created. Work will continue to be made going forward with 4 and implantation improvements will continue. The changelog specifically states breaking changes are in this release. The PR related to this release also documents a reasonable way to use the cookbook. 

Also, there is no stated support for 9.5 yet. So, although it could be assumed that moving to 9.5 packages for some distributions may not be too far off from where things are now, to expect that it would work without issues or without bugs and then complain in a way that says we should revert or ditch work because you are experiencing issue is not a very helpful approach.

The issues which you have raised will be addressed by me directly as time allows. If you would like to actually put some time in on the code that would be great too.

**Comment by sauliusgrigaitis** [comment]
@slyness thanks for response. Just few points:

1) People tend to not read change logs. I personally just ``berks update``` and try on staging. People just use latest release and expect good results.
2) This particular case is very sensitive, because it potentially lead to data loss. Most likely some data will be lost even if there are backups in place.

So if you don't prefer to revert then I would be really great idea to consider at least throwing error if user tries to manage unsupported PostgreSQL version with this cookbook.

**Comment by luckymike** [comment]
@sauliusgrigaitis:

>People just use latest release and expect good results.

This is a really, really risky proposition in the Chef community (and elsewhere). The vast preponderance of community cookbooks use semantic versioning, whereby a major release indicates _breaking changes_. 

Everyone must weigh their own tolerance for risk vs. effort to stay current, but I'd strongly suggest at least pessimistic cookbook constraints (~>).

**Comment by chr4** [comment]
Just a few more thoughts:

- Noone is against releasing major versions with breaking changes.
- Reading changelogs when doing major version upgrades should be done, but in this case [this didn't help](https://github.com/hw-cookbooks/postgresql/pull/326).
- The "just version lock the old version" leaves those alone who are not using Berkshelf (it wasn't always as good as it is now, and it's become the de-facto-standard not very long ago). Furthermore there's people starting to use a cookbook - And they usually start with the latest stable release.
- DO something, when people report dropped databases! ANYTHING. FAST.

**Comment by damacus** [comment]
Thanks for the discussion here. 

We're going to default to 9.6 in the latest release, but also allow easier setting and installing of versions via the custom resource,`server_install` without needing to add attributes for every version !
