### ISSUE TITLE
Specify users as configuration attributes

### ISSUE THREAD

**Issue by stantond** [sous-chefs/postgresql#401]
Are the any plans to allow users to be specified as attributes, like [phlipper/chef-postgresql](https://github.com/phlipper/chef-postgresql)?

For example:
```
"postgresql": {
  "users": [
    {
      "username": "dickeyxxx",
      "password": "password",
      "superuser": true,
      "replication": false,
      "createdb": true,
      "createrole": false,
      "inherit": true,
      "replication": false,
      "login": true
    }
  ]
}
```

**Comment by tas50** [comment]
We probably won't be adding these as attributes since that would save the password attribute to the node where it could be found in the chef server or by anyone with knife access. I do hope to add additional custom resources that would allow you to achieve a similar result in a wrapper cookbook. You could store the values in something like vault or an encrypted databag of your choosing.
