### ISSUE TITLE
Early postgresql_access apply?

### ISSUE THREAD

**Issue by gionn** [sous-chefs/postgresql#557]
I am new with the accumulator pattern, and I am wondering how to deal with it when I need that a resource (e.g. `postgresql_access`) get applied immediately and not until the end of the run, since some other recipes are relying on that.

Thanks.

**Comment by damacus** [comment]
Usually you'd want to put them after the access resource has run in the run list.

If you're trying to share the final state of the file on disk, you probably want to pass that around Chef. Rather than reading from disk post access apply.

If you're waiting for access to apply to you can gain access, putting it early in the run should do the job.

**Comment by gionn** [comment]
> If you're waiting for access to apply to you can gain access, putting it early in the run should do the job.

this, I execute a command that needs to connect to a database, but access is granted only at the end of the run (https://github.com/sous-chefs/postgresql/blob/master/resources/access.rb#L47).

It would be great to have a way to declare that I am done with my `postgres_access` declarations and get things applied before the end of the chef run.

At this time, I am not able to use `postgres_access` and I've reverted to manage `pg_hba.conf` on my own.

**Comment by damacus** [comment]
The access is only granted at the end of the run due to postgresql having a single conf file with multiple uses, thus forcing us to ue the accumulator pattern. [Here's a great write-up of the accumulator pattern](https://blog.dnsimple.com/2017/10/chef-accumulators/). 

you might be able to do all the modifications to the conf file at the start of your config and run your `execute` command near the end, delayed (triggered by something like the access resource)

**Comment by gionn** [comment]
> you might be able to do all the modifications to the conf file at the start of your config and run your execute command near the end, delayed (triggered by something like the access resource)

this may be feasible in simple scenarios but most of my recipes relies on the database ready to accept connections before the end of the run, and as today I had not found a way to use `postgresql_access` resource in my scenario.

**Comment by jimdaga** [comment]
This may help, I worked around this using the `action :nothing` on my commands that require that the database is online and added a notifies/:delayed in one of the `postgresql_access` blocks. This pushed all the database calls to the end, after the configs are wrote.

**Comment by damacus** [comment]
Closing as I'm sure this is the correct approach. Please reopen if this doesn't work!
