### ISSUE TITLE
Peer Authentication failed for "Postgres"

### ISSUE THREAD

**Issue by imrrahul** [sous-chefs/postgresql#601]
I'm having a similar issue - Creating databases in the same Chef run as configuring postgresql seems to me like a regular usecase.
Was there a particular reason the action was changed to `:delayed`?

+1

_Originally posted by @chr4 in https://github.com/sous-chefs/postgresql/issues/232#issuecomment-75782165_

Can be resolved as to solve the error Peer authentication failed go to pg_hba.conf and edit the as local all postgres peer to local all postgres md5 and local all allbpeer to local all all trust the error will resolve .

**Comment by Xorima** [comment]
Hi @alphamuth 

The reason the action is `:delayed` is due to the accumulator pattern being used to build the configuration (see this blog post: https://blog.dnsimple.com/2017/10/chef-accumulators/) 

The easiest way would be to subscribe the template resource,

We should document this behavior better though so when you use the resource it behaves as expected

**Comment by damacus** [comment]
Can you try an add `:delayed` to the resource that depends on the hba_conf please?
